# Generated by Django 3.1.6 on 2021-07-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='amapp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprintId',
            field=models.IntegerField(null=True),
        ),
    ]
