# Generated by Django 3.1.6 on 2021-07-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amapp', '0003_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
