# Generated by Django 3.1.6 on 2021-08-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amapp', '0004_auto_20210702_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
